Catch ValueError exception in fix_payees
Catch the ValueError exception in the fix_payees plugin since
ast.literal_eval can also throw that exception, e.g.:

>>> ast.literal_eval("[() ()]")
...
ValueError: malformed node or string: <_ast.Call object at 0x7f56ad7bfcf8>